name: mention backend auto deployment

on:
  push:
    branches: [ main ]


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: pull the changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MENTION_HOST }}
          username: ${{ secrets.MENTION_USERNAME }}
          password: ${{ secrets.MENTION_PASSWORD }}
          script: |
            cd ${{ secrets.MENTION_PATH }}
            git pull origin main
            composer install
            php artisan migrate
            php artisan optimize